import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/layouts/NavBar";
import Footer from "./components/layouts/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{
        display: 'flex',
        flexDirection: 'column',
        minHeight: '100vh',
        margin: 0
      }}>
        <Navbar />
        <div className="content-wrapper" style={{ 
          paddingTop: '4rem', 
          flex: '1 0 auto' // Hace que este div crezca para ocupar espacio disponible
        }}>
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
